### ISSUE TITLE
Curves for flood damage on crops

### ISSUE THREAD

**Issue by matamadio** [GFDRR/CCDR-tools#22]
We could try to produce something based on this review:

https://link.springer.com/article/10.1007/s11069-022-05791-0

![immagine](https://user-images.githubusercontent.com/44863827/228791082-e5e1d8d8-f24b-454b-afcd-f0cfe256c3e3.png)

Although it is mainly rice crops.

> Vulnerability curves for crops other than cereals should be implemented, given the importance that perennial crops and vegetables have in terms of economic value. Functions for forage crops (alfalfa, pastures or similar) could be useful to evaluate the impacts of extreme events on livestock and have not been considered in none of the reviewed studies.
> 
> The inclusion of field experiments to assess the effect of extremes on the different crop growth stage should be better studied by including field observations in the analysis, rather than using crop models results.

**Comment by stufraser1** [comment]
We developed curve crops in a few recent projects that could be used – and included in the RDL:
R5 SubSaharan Africa (Cima Foundation)
Central Asia (RED)

**Comment by matamadio** [comment]
I see the one in the CIMA R5 report:
![immagine](https://user-images.githubusercontent.com/44863827/228793603-08b9610e-247b-44b6-aace-6f7f6c09ed13.png)

> For vulnerability assessment from floods in agriculture we followed a similar approach to
> the one followed for buildings. For the shape of the curve several sources have been
> compared on damage functions for agriculture: the curve used for agriculture damage in the
> Netherlands (HIS-SSM; Kok et al., 2005), a study on Ho-Chi-Minh City, and a study from
> South Africa by Du Plessis and Viljoen (1997). These curves are shown in the graphs in
> Figure 5.46 below. The curves go up to 100% loss somewhere around 1.5-2 meters. This is
> quite steep, but logical considering whole harvests are lost when the crops drown, for which
> not too much water depth is necessary. Overall, the HIS-SSM curve seems to go quite
> ‘middle of the pack’, and is therefore used in for the flood damage to agriculture. The HISSSM curve is used in the loss computations.

Do we have those also as table? I can't see them in my copy of R5 data.

**Comment by matamadio** [comment]
We are now swtiching to using the JRC function for agricultural areas.

![immagine](https://github.com/GFDRR/CCDR-tools/assets/44863827/ba3e585f-9a87-4d2f-b24c-390033189afd)

![immagine](https://github.com/GFDRR/CCDR-tools/assets/44863827/7a338111-a4c3-44dc-9249-b6814ca28c76)

**Comment by matamadio** [comment]
JRC functions in place as default in the tool.
Will add the chance to edit the functions manually.
