### ISSUE TITLE
Coastal flood - wrong CSV output

### ISSUE THREAD

**Issue by matamadio** [GFDRR/CCDR-tools#8]
The Gpkg is correct, while the csv assign numbers to wrong units.
Happens for Function selection. I don't see how they can be different since is the same dataframe.

```
    if analysis_type == "Function":
        no_geom.to_csv(os.path.join(OUTPUT_DIR, f"{country}_CF_{adm_name}_{exp_cat}_EAI.csv"), index=False)
        result_df.to_file(os.path.join(OUTPUT_DIR, f"{country}_CF_{adm_name}_{exp_cat}_EAI.gpkg"))
```

**Comment by ConnectedSystems** [comment]
Weird! Which notebook does this occur in?

**Comment by ConnectedSystems** [comment]
Nevermind, saw you put it in the title

**Comment by matamadio** [comment]
Coastal flood is the same code as river flood, adapted to work on different source. But that shouldn't affect results. Checking other countries.

**Comment by ConnectedSystems** [comment]
Hmm, could you attach example CSV results with the incorrect values, and let me know what the correct/expected value is? 

Looking over the code I don't see anything wrong.

Also, are you looking at the CSV in Excel? Could it be applying some strange auto-format?

**Comment by matamadio** [comment]
Going to run the code again and see if the error replicates

**Comment by matamadio** [comment]
Bugged output
https://github.com/GFDRR/CCDR-tools/tree/sandbox/Top-down/notebooks/test_results

**Comment by matamadio** [comment]
Bug was in my brain.
